### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'ListWrapper'

### ISSUE THREAD

**Issue by LouisNUST** [murdockhou/Single-Stage-Multi-person-Pose-Machines#1]
Traceback (most recent call last):
  File "/home/louis/Documents/DetPose/Single-Stage-Multi-person-Pose-Machines/main.py", line 28, in <module>
    outputs = SpmModel(inputs, num_joints=['joints'], is_training=True)
  File "/home/louis/Documents/DetPose/Single-Stage-Multi-person-Pose-Machines/nets/spm_model.py", line 21, in SpmModel
    displacement = head_net(body, 2*num_joints, name='reg_map', bn=False)
  File "/home/louis/Documents/DetPose/Single-Stage-Multi-person-Pose-Machines/nets/spm_model.py", line 34, in head_net
    kernel_initializer=tf.random_normal_initializer(stddev=0.01), name=name + '_conv1x1')(out)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 817, in __call__
    self._maybe_build(inputs)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2141, in _maybe_build
    self.build(input_shapes)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 165, in build
    dtype=self.dtype)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 522, in add_weight
    aggregation=aggregation)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 744, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 126, in make_variable
    variable_shape = tensor_shape.TensorShape(shape)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 776, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 718, in as_dimension
    return Dimension(value)
  File "/home/louis/anaconda3/envs/tf-gpu-10/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 193, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'ListWrapper'

the conda environment as follows:
cudatoolkit               10.0.130                      0  
imgaug                    0.3.0                    pypi_0    pypi
python                    3.6.9                h265db76_0  
pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
tensorflow-estimator      2.0.0                    pypi_0    pypi
tensorflow-gpu            2.0.0                    pypi_0    pypi
torchvision               0.4.0                py36_cu100    pytorch

**Comment by murdockhou** [comment]
@LouisNUST 
Hi, i have not met this error before. And based on my knowledge, it's sorry for that can not help you.
